import type { AccordVector } from "./accords";

// ============================================================================
// Knowledge base (seed). Tiap parfum = vektor accord (DNA) + notes + atribut.
// Nilai accord/atribut adalah estimasi dari pengetahuan komposisi umum; blurb
// ditulis ulang (bukan salinan teks pihak lain). Untuk produksi, data ini
// diperkaya/diverifikasi lewat partner (retailer & decant seller).
// ============================================================================

export type Gender = "masc" | "fem" | "uni";

export interface Perfume {
  id: string;
  name: string;
  brand: string;
  year: number;
  gender: Gender;
  /** 1 = terjangkau … 5 = mewah / niche. */
  priceTier: 1 | 2 | 3 | 4 | 5;
  priceIDR: string;
  /** DNA aroma: bobot 0..1 per accord. */
  accords: AccordVector;
  notes: { top: string[]; heart: string[]; base: string[] };
  /** 0..1 — daya tahan di kulit. */
  longevity: number;
  /** 0..1 — proyeksi / seberapa "kecium dari jauh". */
  sillage: number;
  /** 0..1 — kecocokan di iklim panas-lembab (untuk rerank tropis). */
  summerFriendly: number;
  blurb: string;
  /** id parfum acuan bila ini klon/alternatif terjangkau. */
  dupeOf?: string;
}

export const PERFUMES: Perfume[] = [
  {
    id: "sauvage",
    name: "Sauvage EDT",
    brand: "Dior",
    year: 2015,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,2jt",
    accords: { citrus: 0.5, fresh: 0.5, spicy_fresh: 0.7, ambery: 0.6, woody: 0.5, aromatic: 0.4 },
    notes: { top: ["Bergamot", "Lada"], heart: ["Sichuan pepper", "Lavender", "Geranium"], base: ["Ambroxan", "Cedar", "Labdanum"] },
    longevity: 0.75, sillage: 0.85, summerFriendly: 0.8,
    blurb: "Fresh-spicy ambroxan yang gampang disukai — workhorse serba bisa buat cuaca panas.",
  },
  {
    id: "bleu-de-chanel",
    name: "Bleu de Chanel EDP",
    brand: "Chanel",
    year: 2014,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,5jt",
    accords: { citrus: 0.5, aromatic: 0.6, woody: 0.7, fresh: 0.5, ambery: 0.4, spicy_fresh: 0.3 },
    notes: { top: ["Grapefruit", "Lemon", "Mint"], heart: ["Ginger", "Nutmeg", "Jasmine"], base: ["Cedar", "Sandalwood", "Amber"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.75,
    blurb: "Woody-aromatic elegan, aman buat kantor sampai formal. Fresh tapi berkelas.",
  },
  {
    id: "acqua-di-gio",
    name: "Acqua di Giò EDT",
    brand: "Giorgio Armani",
    year: 1996,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { aquatic_ozonic: 0.8, citrus: 0.6, fresh: 0.6, aromatic: 0.3, musky: 0.3 },
    notes: { top: ["Bergamot", "Neroli", "Jeruk"], heart: ["Rosemary", "Jasmine", "Sea notes"], base: ["Musk", "Patchouli", "Amber"] },
    longevity: 0.55, sillage: 0.5, summerFriendly: 0.95,
    blurb: "Aquatic klasik. Definisi 'wangi segar bersih' buat siang bolong yang gerah.",
  },
  {
    id: "aventus",
    name: "Aventus",
    brand: "Creed",
    year: 2010,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp4jt–6jt",
    accords: { fruity: 0.7, smoky: 0.6, woody: 0.6, mossy_chypre: 0.4, musky: 0.3, citrus: 0.3 },
    notes: { top: ["Nanas", "Blackcurrant", "Bergamot"], heart: ["Birch", "Patchouli", "Jasmine"], base: ["Oakmoss", "Musk", "Vanilla"] },
    longevity: 0.8, sillage: 0.8, summerFriendly: 0.75,
    blurb: "Nanas berasap yang jadi legenda. Percaya diri, maskulin, pas buat 'statement'.",
  },
  {
    id: "coco-mademoiselle",
    name: "Coco Mademoiselle EDP",
    brand: "Chanel",
    year: 2001,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { floral: 0.7, mossy_chypre: 0.6, fruity: 0.4, powdery: 0.4, ambery: 0.3, citrus: 0.3 },
    notes: { top: ["Jeruk", "Bergamot"], heart: ["Mawar", "Jasmine", "Lychee"], base: ["Patchouli", "Vanilla", "Vetiver"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.6,
    blurb: "Floral-chypre ikonik. Feminin, dewasa, dan langsung dikenali.",
  },
  {
    id: "black-opium",
    name: "Black Opium EDP",
    brand: "YSL",
    year: 2014,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,3jt",
    accords: { gourmand: 0.7, sweet: 0.7, vanilla: 0.5, floral: 0.4, spicy_warm: 0.3 },
    notes: { top: ["Kopi", "Pear", "Pink pepper"], heart: ["Jasmine", "Bunga jeruk"], base: ["Vanilla", "Patchouli", "Cedar"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.45,
    blurb: "Kopi-vanila yang adiktif. Vibe malam, seductive, cocok cuaca sejuk/AC.",
  },
  {
    id: "la-vie-est-belle",
    name: "La Vie Est Belle EDP",
    brand: "Lancôme",
    year: 2012,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { sweet: 0.7, gourmand: 0.6, powdery: 0.5, floral: 0.5, vanilla: 0.4, fruity: 0.3 },
    notes: { top: ["Blackcurrant", "Pear"], heart: ["Iris", "Jasmine", "Bunga jeruk"], base: ["Praline", "Vanilla", "Patchouli"] },
    longevity: 0.85, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Iris-praline manis lembut. Manis tapi elegan, bukan gula-gula.",
  },
  {
    id: "baccarat-rouge-540",
    name: "Baccarat Rouge 540 EDP",
    brand: "Maison Francis Kurkdjian",
    year: 2015,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4,5jt–6,5jt",
    accords: { sweet: 0.7, ambery: 0.7, woody: 0.6, floral: 0.3, powdery: 0.3 },
    notes: { top: ["Saffron", "Jasmine"], heart: ["Amberwood", "Cedar"], base: ["Fir resin", "Musk"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.55,
    blurb: "Saffron-amberwood manis yang 'mahal banget kedengarannya'. Sinar & tembus.",
  },
  {
    id: "santal-33",
    name: "Santal 33 EDP",
    brand: "Le Labo",
    year: 2011,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { woody: 0.9, musky: 0.4, leather: 0.4, spicy_warm: 0.3 },
    notes: { top: ["Cardamom", "Violet"], heart: ["Iris", "Ambrox"], base: ["Sandalwood", "Cedar", "Leather"] },
    longevity: 0.8, sillage: 0.6, summerFriendly: 0.6,
    blurb: "Sandalwood-leather kering yang uniseks banget. Cool, effortless, 'kota'.",
  },
  {
    id: "tobacco-vanille",
    name: "Tobacco Vanille EDP",
    brand: "Tom Ford",
    year: 2007,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { gourmand: 0.7, vanilla: 0.7, spicy_warm: 0.7, sweet: 0.5, woody: 0.3 },
    notes: { top: ["Tembakau", "Rempah"], heart: ["Vanilla", "Cocoa", "Tonka"], base: ["Kayu kering", "Buah kering"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.25,
    blurb: "Tembakau-vanila hangat & mewah. Musuh cuaca panas, raja musim dingin/AC.",
  },
  {
    id: "oud-wood",
    name: "Oud Wood EDP",
    brand: "Tom Ford",
    year: 2007,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { woody: 0.8, animalic: 0.5, spicy_warm: 0.4, smoky: 0.3 },
    notes: { top: ["Oud", "Cardamom", "Lada"], heart: ["Sandalwood", "Vetiver"], base: ["Tonka", "Vanilla", "Amber"] },
    longevity: 0.8, sillage: 0.55, summerFriendly: 0.5,
    blurb: "Oud yang halus & 'sopan' — gerbang oud buat pemula. Mewah dan tenang.",
  },
  {
    id: "light-blue",
    name: "Light Blue EDT",
    brand: "Dolce & Gabbana",
    year: 2001,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { citrus: 0.7, fresh: 0.6, fruity: 0.5, musky: 0.3, woody: 0.2 },
    notes: { top: ["Lemon Sisilia", "Apel"], heart: ["Bamboo", "Mawar putih"], base: ["Cedar", "Musk", "Amber"] },
    longevity: 0.5, sillage: 0.5, summerFriendly: 0.95,
    blurb: "Lemon-apel segar yang ceria. Aroma liburan pantai; ringan buat harian.",
  },
  {
    id: "le-male",
    name: "Le Male EDT",
    brand: "Jean Paul Gaultier",
    year: 1995,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,6jt",
    accords: { aromatic: 0.7, sweet: 0.6, vanilla: 0.5, fresh: 0.4, spicy_warm: 0.3 },
    notes: { top: ["Mint", "Lavender", "Bergamot"], heart: ["Cinnamon", "Cumin", "Bunga jeruk"], base: ["Vanilla", "Tonka", "Cedar"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.6,
    blurb: "Lavender-vanila 'barbershop manis' yang legendaris. Bersih tapi hangat.",
  },
  {
    id: "eros",
    name: "Eros EDT",
    brand: "Versace",
    year: 2012,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { aromatic: 0.6, sweet: 0.6, fresh: 0.5, vanilla: 0.5, woody: 0.3 },
    notes: { top: ["Mint", "Apel hijau", "Lemon"], heart: ["Tonka", "Geranium"], base: ["Vanilla", "Vetiver", "Cedar"] },
    longevity: 0.85, sillage: 0.85, summerFriendly: 0.6,
    blurb: "Mint-vanila manis segar. Crowd-pleaser buat anak muda, proyeksi galak.",
  },
  {
    id: "one-million",
    name: "1 Million EDT",
    brand: "Paco Rabanne",
    year: 2008,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,5jt",
    accords: { spicy_warm: 0.6, sweet: 0.6, leather: 0.5, woody: 0.3, citrus: 0.3 },
    notes: { top: ["Grapefruit", "Mint", "Blood mandarin"], heart: ["Rose", "Cinnamon", "Rempah"], base: ["Leather", "Amber", "Patchouli"] },
    longevity: 0.8, sillage: 0.8, summerFriendly: 0.5,
    blurb: "Rempah-kulit manis yang berani. Malam hari, penuh percaya diri.",
  },
  {
    id: "la-nuit-de-lhomme",
    name: "La Nuit de L'Homme EDT",
    brand: "YSL",
    year: 2009,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,7jt",
    accords: { spicy_warm: 0.6, aromatic: 0.5, woody: 0.4, ambery: 0.4, powdery: 0.3 },
    notes: { top: ["Cardamom", "Bergamot"], heart: ["Lavender", "Cedar"], base: ["Vetiver", "Tonka"] },
    longevity: 0.6, sillage: 0.6, summerFriendly: 0.65,
    blurb: "Cardamom-cedar yang seksi tapi lembut. Aroma 'date night' andalan.",
  },
  {
    id: "dior-homme-intense",
    name: "Dior Homme Intense EDP",
    brand: "Dior",
    year: 2011,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,3jt",
    accords: { powdery: 0.8, floral: 0.5, woody: 0.5, ambery: 0.3 },
    notes: { top: ["Lavender"], heart: ["Iris", "Ambrette", "Pear"], base: ["Vetiver", "Cedar"] },
    longevity: 0.85, sillage: 0.7, summerFriendly: 0.4,
    blurb: "Iris powdery yang mewah & maskulin sekaligus. Formal, penuh kelas.",
  },
  {
    id: "chanel-no5",
    name: "N°5 EDP",
    brand: "Chanel",
    year: 1921,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { powdery: 0.7, floral: 0.7, fresh: 0.3, musky: 0.3, aromatic: 0.2 },
    notes: { top: ["Aldehid", "Neroli", "Ylang-ylang"], heart: ["Mawar", "Jasmine", "Iris"], base: ["Sandalwood", "Vanilla", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Aldehyde-floral bedak yang abadi. Klasik, anggun, timeless.",
  },
  {
    id: "gucci-bloom",
    name: "Bloom EDP",
    brand: "Gucci",
    year: 2017,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,4jt–2,1jt",
    accords: { white_floral: 0.9, floral: 0.5, powdery: 0.3 },
    notes: { top: ["Bunga jeruk"], heart: ["Tuberose", "Jasmine"], base: ["Orris", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Tuberose mekar penuh. Feminin klasik, bunga putih yang 'ramai'.",
  },
  {
    id: "daisy",
    name: "Daisy EDT",
    brand: "Marc Jacobs",
    year: 2007,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1jt–1,6jt",
    accords: { floral: 0.6, fresh: 0.5, fruity: 0.4, woody: 0.2, musky: 0.2 },
    notes: { top: ["Strawberry", "Grapefruit"], heart: ["Violet", "Gardenia"], base: ["Musk", "Vanilla", "Kayu"] },
    longevity: 0.5, sillage: 0.5, summerFriendly: 0.85,
    blurb: "Floral segar yang muda & ringan. Manis lembut buat harian.",
  },
  {
    id: "narciso-for-her",
    name: "For Her EDP",
    brand: "Narciso Rodriguez",
    year: 2006,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,4jt–2jt",
    accords: { musky: 0.8, floral: 0.4, woody: 0.4, powdery: 0.3, ambery: 0.3 },
    notes: { top: ["Bunga jeruk", "Osmanthus"], heart: ["Musk", "Amber"], base: ["Vetiver", "Vanilla", "Patchouli"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Musk-woody sensual yang 'kulit banget'. Bikin orang penasaran dari dekat.",
  },
  {
    id: "ysl-libre",
    name: "Libre EDP",
    brand: "YSL",
    year: 2019,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,4jt",
    accords: { aromatic: 0.6, floral: 0.6, vanilla: 0.4, white_floral: 0.3, musky: 0.3 },
    notes: { top: ["Lavender", "Mandarin"], heart: ["Bunga jeruk", "Jasmine"], base: ["Vanilla", "Musk", "Cedar"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.6,
    blurb: "Lavender-bunga jeruk modern. Feminin tapi ada sisi 'tegas' yang keren.",
  },
  {
    id: "good-girl",
    name: "Good Girl EDP",
    brand: "Carolina Herrera",
    year: 2016,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,3jt",
    accords: { sweet: 0.6, white_floral: 0.5, gourmand: 0.5, vanilla: 0.4, spicy_warm: 0.3, ambery: 0.3 },
    notes: { top: ["Almond", "Kopi"], heart: ["Tuberose", "Jasmine"], base: ["Tonka", "Cocoa", "Vanilla"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.45,
    blurb: "Almond-tuberose manis-gelap. Berani, malam hari, penuh drama (sepatu hak itu).",
  },
  {
    id: "flowerbomb",
    name: "Flowerbomb EDP",
    brand: "Viktor&Rolf",
    year: 2005,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,4jt",
    accords: { sweet: 0.7, floral: 0.6, white_floral: 0.4, fruity: 0.3, powdery: 0.3 },
    notes: { top: ["Teh", "Bergamot"], heart: ["Jasmine", "Mawar", "Orchid"], base: ["Patchouli", "Musk", "Vanilla"] },
    longevity: 0.85, sillage: 0.75, summerFriendly: 0.45,
    blurb: "Ledakan bunga manis. Girly, hangat, memeluk — favorit sejuta umat.",
  },
  {
    id: "prada-lhomme",
    name: "L'Homme EDT",
    brand: "Prada",
    year: 2016,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,7jt",
    accords: { powdery: 0.6, aromatic: 0.5, woody: 0.4, musky: 0.4, floral: 0.3 },
    notes: { top: ["Neroli", "Lada", "Cardamom"], heart: ["Iris", "Geranium", "Violet"], base: ["Amber", "Cedar", "Patchouli"] },
    longevity: 0.7, sillage: 0.55, summerFriendly: 0.7,
    blurb: "Iris-neroli bersih & bedak. Rapi, wangi 'cowok well-groomed'.",
  },
  {
    id: "chance-eau-tendre",
    name: "Chance Eau Tendre EDP",
    brand: "Chanel",
    year: 2010,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,5jt",
    accords: { fruity: 0.6, floral: 0.5, fresh: 0.5, citrus: 0.3, musky: 0.3 },
    notes: { top: ["Grapefruit", "Quince"], heart: ["Hyacinth", "Jasmine"], base: ["Musk", "Amber", "Iris"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.9,
    blurb: "Grapefruit-jasmine segar-manis. Ringan, bersih, cocok harian tropis.",
  },
  {
    id: "nautica-voyage",
    name: "Voyage EDT",
    brand: "Nautica",
    year: 2006,
    gender: "masc",
    priceTier: 1,
    priceIDR: "Rp150rb–300rb",
    accords: { aquatic_ozonic: 0.7, fresh: 0.6, citrus: 0.4, woody: 0.3, fruity: 0.3 },
    notes: { top: ["Apel", "Air"], heart: ["Mimosa", "Water lily", "Lotus"], base: ["Musk", "Cedar", "Amber"] },
    longevity: 0.55, sillage: 0.5, summerFriendly: 0.95,
    blurb: "Aquatic-apel murah meriah yang wanginya jauh di atas harganya. Raja value.",
  },
  {
    id: "dylan-blue",
    name: "Dylan Blue EDT",
    brand: "Versace",
    year: 2016,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { aquatic_ozonic: 0.6, aromatic: 0.5, citrus: 0.4, woody: 0.4, musky: 0.3 },
    notes: { top: ["Bergamot", "Grapefruit", "Fig leaf"], heart: ["Violet", "Papyrus", "Pepper"], base: ["Musk", "Incense", "Patchouli"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.75,
    blurb: "Aquatic-aromatic modern yang tegas. Segar tapi 'ada isinya', tahan lama.",
  },
  {
    id: "by-the-fireplace",
    name: "Replica By the Fireplace EDT",
    brand: "Maison Margiela",
    year: 2015,
    gender: "uni",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { smoky: 0.7, gourmand: 0.6, sweet: 0.4, vanilla: 0.4, woody: 0.3 },
    notes: { top: ["Pink pepper", "Cengkeh"], heart: ["Chestnut", "Guaiac wood"], base: ["Vanilla", "Cashmeran", "Peru balsam"] },
    longevity: 0.75, sillage: 0.65, summerFriendly: 0.3,
    blurb: "Kastanye panggang berasap-manis. Cozy 'perapian'; juara cuaca dingin/hujan.",
  },
  {
    id: "glossier-you",
    name: "You EDP",
    brand: "Glossier",
    year: 2017,
    gender: "uni",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { musky: 0.7, powdery: 0.4, spicy_fresh: 0.4, ambery: 0.3 },
    notes: { top: ["Pink pepper"], heart: ["Iris", "Ambrette", "Ambrox"], base: ["Musk", "Kayu"] },
    longevity: 0.6, sillage: 0.4, summerFriendly: 0.7,
    blurb: "Musk-iris yang nyatu jadi 'versi kamu tapi lebih wangi'. Intim, skin scent.",
  },
  {
    id: "grand-soir",
    name: "Grand Soir EDP",
    brand: "Maison Francis Kurkdjian",
    year: 2016,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { ambery: 0.8, vanilla: 0.7, sweet: 0.4, powdery: 0.3 },
    notes: { top: ["Bunga jeruk"], heart: ["Amber", "Benzoin"], base: ["Vanilla", "Tonka", "Labdanum"] },
    longevity: 0.9, sillage: 0.8, summerFriendly: 0.35,
    blurb: "Amber-vanila hangat yang mewah dan memeluk. Malam elegan, cuaca dingin.",
  },
  {
    id: "layton",
    name: "Layton EDP",
    brand: "Parfums de Marly",
    year: 2016,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { sweet: 0.6, spicy_warm: 0.5, vanilla: 0.5, fruity: 0.4, aromatic: 0.4, powdery: 0.3 },
    notes: { top: ["Apel", "Lavender", "Bergamot"], heart: ["Geranium", "Violet", "Jasmine"], base: ["Vanilla", "Cardamom", "Sandalwood"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.5,
    blurb: "Apel-lavender-vanila yang mewah & serba bisa. Manis dewasa, bukan kekanakan.",
  },
  {
    id: "oud-for-greatness",
    name: "Oud for Greatness EDP",
    brand: "Initio",
    year: 2018,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { animalic: 0.7, smoky: 0.5, spicy_warm: 0.5, woody: 0.5, mossy_chypre: 0.3 },
    notes: { top: ["Saffron", "Nutmeg", "Lavender"], heart: ["Oud", "Patchouli"], base: ["Musk", "Amber"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.4,
    blurb: "Saffron-oud yang gagah & tembus ruangan. Statement scent buat yang berani.",
  },
  {
    id: "naxos",
    name: "Naxos EDP",
    brand: "Xerjoff",
    year: 2015,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4,5jt–6,5jt",
    accords: { gourmand: 0.7, sweet: 0.6, spicy_warm: 0.5, aromatic: 0.5, vanilla: 0.4, smoky: 0.3 },
    notes: { top: ["Bergamot", "Lavender", "Honey"], heart: ["Cinnamon", "Cashmeran"], base: ["Tembakau", "Vanilla", "Tonka"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    blurb: "Madu-tembakau-lavender yang mewah & manis. 'Baklava' versi parfum.",
  },
  {
    id: "cdnim",
    name: "Club de Nuit Intense Man EDT",
    brand: "Armaf",
    year: 2015,
    gender: "masc",
    priceTier: 2,
    priceIDR: "Rp300rb–500rb",
    accords: { fruity: 0.7, smoky: 0.6, woody: 0.5, mossy_chypre: 0.3, musky: 0.3, citrus: 0.3 },
    notes: { top: ["Nanas", "Lemon", "Blackcurrant"], heart: ["Birch", "Jasmine"], base: ["Musk", "Vanilla", "Oakmoss"] },
    longevity: 0.85, sillage: 0.9, summerFriendly: 0.7,
    dupeOf: "aventus",
    blurb: "Alternatif Aventus paling terkenal — 90% mirip, harga sepersepuluh. Proyeksi monster.",
  },
  {
    id: "khamrah",
    name: "Khamrah EDP",
    brand: "Lattafa",
    year: 2022,
    gender: "uni",
    priceTier: 2,
    priceIDR: "Rp250rb–450rb",
    accords: { spicy_warm: 0.7, gourmand: 0.6, sweet: 0.6, vanilla: 0.5, ambery: 0.3 },
    notes: { top: ["Cinnamon", "Nutmeg", "Bergamot"], heart: ["Kurma", "Praline", "Tuberose"], base: ["Vanilla", "Tonka", "Benzoin"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    dupeOf: "naxos",
    blurb: "Kayu manis-kurma-vanila yang hangat & manis. Viral, murah, cocok malam & cuaca dingin.",
  },
  {
    id: "asad",
    name: "Asad EDP",
    brand: "Lattafa",
    year: 2022,
    gender: "masc",
    priceTier: 1,
    priceIDR: "Rp180rb–350rb",
    accords: { sweet: 0.6, spicy_warm: 0.5, fruity: 0.5, vanilla: 0.4, ambery: 0.3, woody: 0.3 },
    notes: { top: ["Nanas", "Lada hitam"], heart: ["Tembakau", "Vetiver"], base: ["Vanilla", "Amber", "Kopi"] },
    longevity: 0.8, sillage: 0.85, summerFriendly: 0.5,
    blurb: "Nanas-tembakau-vanila manis dengan proyeksi galak. Value luar biasa buat 'malam murah'.",
  },
  {
    id: "ck-one",
    name: "CK One EDT",
    brand: "Calvin Klein",
    year: 1994,
    gender: "uni",
    priceTier: 2,
    priceIDR: "Rp400rb–700rb",
    accords: { citrus: 0.7, fresh: 0.6, musky: 0.4, aromatic: 0.3 },
    notes: { top: ["Lemon", "Bergamot", "Nanas"], heart: ["Teh hijau", "Violet", "Nutmeg"], base: ["Musk", "Amber", "Cedar"] },
    longevity: 0.4, sillage: 0.4, summerFriendly: 0.9,
    blurb: "Citrus-teh uniseks yang bersih & simpel. Ringan banget; segar buat siapa saja.",
  },
  {
    id: "wood-sage-sea-salt",
    name: "Wood Sage & Sea Salt Cologne",
    brand: "Jo Malone",
    year: 2014,
    gender: "uni",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { aquatic_ozonic: 0.6, fresh: 0.6, mossy_chypre: 0.3, woody: 0.3, aromatic: 0.3 },
    notes: { top: ["Ambrette", "Garam laut"], heart: ["Sage"], base: ["Kayu driftwood", "Grapefruit"] },
    longevity: 0.5, sillage: 0.45, summerFriendly: 0.9,
    blurb: "Garam laut-sage mineral yang minimalis & mahal-terdengar. Angin pantai, effortless.",
  },
  {
    id: "molecule-01",
    name: "Molecule 01",
    brand: "Escentric Molecules",
    year: 2006,
    gender: "uni",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { woody: 0.5, musky: 0.5, ambery: 0.3 },
    notes: { top: [], heart: ["Iso E Super"], base: ["Kayu velvety"] },
    longevity: 0.6, sillage: 0.5, summerFriendly: 0.75,
    blurb: "Satu bahan (Iso E Super) — kayu-musk transparan yang nempel di kulit. Aroma 'aura', bukan parfum.",
  },
  {
    id: "sauvage-elixir",
    name: "Sauvage Elixir",
    brand: "Dior",
    year: 2021,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp2jt–2,8jt",
    accords: { spicy_warm: 0.7, ambery: 0.6, aromatic: 0.5, woody: 0.4, sweet: 0.3, citrus: 0.3 },
    notes: { top: ["Cinnamon", "Nutmeg", "Grapefruit"], heart: ["Lavender", "Licorice"], base: ["Amber", "Sandalwood", "Tonka"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.3,
    blurb: "Versi elixir Sauvage — lebih pekat, manis-rempah-lavender. Malam & cuaca sejuk.",
  },
  {
    id: "allure-homme-sport",
    name: "Allure Homme Sport",
    brand: "Chanel",
    year: 2004,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,3jt",
    accords: { citrus: 0.6, aromatic: 0.5, fresh: 0.5, woody: 0.4, aquatic_ozonic: 0.4, musky: 0.3 },
    notes: { top: ["Orange", "Sea notes", "Aldehydes"], heart: ["Pepper", "Cedar", "Neroli"], base: ["Tonka", "Musk", "Vetiver"] },
    longevity: 0.75, sillage: 0.6, summerFriendly: 0.9,
    blurb: "Citrus-woody bersih yang segar seharian. Aman banget buat panas & kantor.",
  },
  {
    id: "adg-profumo",
    name: "Acqua di Giò Profumo",
    brand: "Giorgio Armani",
    year: 2015,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { aquatic_ozonic: 0.6, smoky: 0.4, aromatic: 0.4, woody: 0.4, mossy_chypre: 0.3, citrus: 0.3 },
    notes: { top: ["Bergamot", "Marine notes"], heart: ["Geranium", "Sage", "Rosemary"], base: ["Incense", "Patchouli"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.75,
    blurb: "Acqua di Gio versi gelap & elegan — aquatic dengan dupa. Naik kelas buat malam.",
  },
  {
    id: "eros-flame",
    name: "Eros Flame",
    brand: "Versace",
    year: 2018,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,6jt",
    accords: { fruity: 0.5, spicy_warm: 0.5, woody: 0.4, aromatic: 0.4, sweet: 0.4, citrus: 0.3 },
    notes: { top: ["Lemon", "Black pepper", "Rosemary"], heart: ["Pepper", "Geranium", "Rose"], base: ["Tonka", "Vanilla", "Cedar"] },
    longevity: 0.8, sillage: 0.8, summerFriendly: 0.5,
    blurb: "Versi hangat dari Eros — lemon-rempah-tonka. Manis maskulin buat malam.",
  },
  {
    id: "man-in-black",
    name: "Man in Black",
    brand: "Bvlgari",
    year: 2014,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,5jt",
    accords: { ambery: 0.6, spicy_warm: 0.5, leather: 0.5, sweet: 0.4, floral: 0.3, vanilla: 0.3 },
    notes: { top: ["Bergamot", "Pink pepper"], heart: ["Rum", "Tuberose", "Iris"], base: ["Leather", "Tonka", "Amber"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    blurb: "Rum-kulit-tuberose yang dewasa & seksi. Statement malam yang murah tapi mewah.",
  },
  {
    id: "explorer",
    name: "Explorer",
    brand: "Montblanc",
    year: 2019,
    gender: "masc",
    priceTier: 2,
    priceIDR: "Rp600rb–1jt",
    accords: { woody: 0.5, fresh: 0.4, leather: 0.3, mossy_chypre: 0.3, citrus: 0.3, ambery: 0.3 },
    notes: { top: ["Bergamot", "Pink pepper"], heart: ["Vetiver", "Leather"], base: ["Patchouli", "Ambroxan"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.7,
    blurb: "Woody-vetiver segar dengan value gila. Sering disebut 'Aventus versi ekonomis'.",
  },
  {
    id: "wanted",
    name: "Wanted",
    brand: "Azzaro",
    year: 2016,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { spicy_warm: 0.5, woody: 0.4, citrus: 0.4, sweet: 0.4, aromatic: 0.3 },
    notes: { top: ["Lemon", "Ginger", "Cardamom"], heart: ["Vetiver", "Sage"], base: ["Tonka", "Amberwood"] },
    longevity: 0.7, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Cardamom-lemon-tonka yang smooth & cerah. Serba bisa buat harian.",
  },
  {
    id: "luna-rossa-carbon",
    name: "Luna Rossa Carbon",
    brand: "Prada",
    year: 2017,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { aromatic: 0.6, aquatic_ozonic: 0.4, woody: 0.4, fresh: 0.4, spicy_fresh: 0.3, ambery: 0.3 },
    notes: { top: ["Bergamot", "Lavender"], heart: ["Coal", "Pepper"], base: ["Ambroxan", "Patchouli"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.75,
    blurb: "Lavender-ambroxan modern yang clean & 'metalik' keren. Kantor sampai malam.",
  },
  {
    id: "fahrenheit",
    name: "Fahrenheit",
    brand: "Dior",
    year: 1988,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { leather: 0.6, floral: 0.4, woody: 0.4, aromatic: 0.3, powdery: 0.3 },
    notes: { top: ["Violet leaf", "Mandarin"], heart: ["Violet", "Nutmeg"], base: ["Leather", "Vetiver", "Amber"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Kulit-violet-'bensin' yang ikonik & polarizing. Unik, dewasa, timeless.",
  },
  {
    id: "idole",
    name: "Idôle EDP",
    brand: "Lancôme",
    year: 2019,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,4jt–2jt",
    accords: { floral: 0.6, musky: 0.5, powdery: 0.3, fruity: 0.3 },
    notes: { top: ["Pear", "Bergamot"], heart: ["Rose", "Jasmine"], base: ["Musk", "Vanilla", "Cedar"] },
    longevity: 0.7, sillage: 0.6, summerFriendly: 0.8,
    blurb: "Mawar-musk bersih yang ringan & modern. Feminin buat harian.",
  },
  {
    id: "mon-paris",
    name: "Mon Paris EDP",
    brand: "YSL",
    year: 2016,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { fruity: 0.6, sweet: 0.6, floral: 0.5, mossy_chypre: 0.3, ambery: 0.3 },
    notes: { top: ["Strawberry", "Raspberry", "Orange"], heart: ["Peony", "Jasmine", "Datura"], base: ["Patchouli", "White musk"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.5,
    blurb: "Strawberry-patchouli manis yang seductive. Malam buat penyuka buah manis.",
  },
  {
    id: "chloe-edp",
    name: "Chloé EDP",
    brand: "Chloé",
    year: 2008,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { floral: 0.7, powdery: 0.5, musky: 0.3 },
    notes: { top: ["Peony", "Freesia", "Lychee"], heart: ["Rose", "Lily"], base: ["Cedar", "Amber", "Musk"] },
    longevity: 0.7, sillage: 0.65, summerFriendly: 0.7,
    blurb: "Mawar-powdery klasik yang anggun. Feminin 'wangi cewek rapi'.",
  },
  {
    id: "mj-perfect",
    name: "Perfect EDP",
    brand: "Marc Jacobs",
    year: 2020,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { floral: 0.5, fruity: 0.5, fresh: 0.4, gourmand: 0.3, musky: 0.3 },
    notes: { top: ["Rhubarb", "Daffodil"], heart: ["Almond milk", "Orris"], base: ["Cashmeran", "Cedar"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.8,
    blurb: "Rhubarb-almond milk yang fresh & feel-good. Harian yang ceria.",
  },
  {
    id: "paradoxe",
    name: "Paradoxe EDP",
    brand: "Prada",
    year: 2022,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,3jt",
    accords: { floral: 0.6, ambery: 0.4, musky: 0.4, white_floral: 0.3, fruity: 0.3 },
    notes: { top: ["Bergamot", "Pear"], heart: ["Jasmine", "Neroli"], base: ["Amber", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Jasmine-amber modern yang bold tapi ramah. Feminin serba suasana.",
  },
  {
    id: "burberry-her",
    name: "Her EDP",
    brand: "Burberry",
    year: 2018,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { fruity: 0.6, sweet: 0.5, gourmand: 0.4, musky: 0.3, floral: 0.3 },
    notes: { top: ["Blackcurrant", "Berries"], heart: ["Violet", "Jasmine"], base: ["Musk", "Amber", "Patchouli"] },
    longevity: 0.75, sillage: 0.7, summerFriendly: 0.65,
    blurb: "Beri-musk manis yang playful & nagih. Anak muda banget.",
  },
  {
    id: "the-only-one",
    name: "The Only One EDP",
    brand: "Dolce & Gabbana",
    year: 2018,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { gourmand: 0.5, floral: 0.5, sweet: 0.4, vanilla: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Bergamot"], heart: ["Coffee", "Orange blossom"], base: ["Vanilla", "Patchouli"] },
    longevity: 0.75, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Kopi-bunga jeruk yang hangat & modern. Alternatif Black Opium yang lebih dewasa.",
  },
  {
    id: "kayali-vanilla-28",
    name: "Vanilla | 28 EDP",
    brand: "Kayali",
    year: 2018,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { vanilla: 0.8, gourmand: 0.6, sweet: 0.6, ambery: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Brown sugar", "Bergamot"], heart: ["Vanilla orchid", "Jasmine"], base: ["Vanilla", "Musk", "Amber"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.4,
    blurb: "Vanila-brown sugar yang tebal & nagih. Cozy, manis, wajib buat sweet lover.",
  },
  {
    id: "cloud",
    name: "Cloud EDP",
    brand: "Ariana Grande",
    year: 2018,
    gender: "fem",
    priceTier: 2,
    priceIDR: "Rp600rb–1jt",
    accords: { gourmand: 0.6, sweet: 0.6, vanilla: 0.4, powdery: 0.3, musky: 0.3 },
    notes: { top: ["Lavender", "Pear", "Bergamot"], heart: ["Whipped cream", "Praline", "Coconut"], base: ["Musk", "Vanilla"] },
    longevity: 0.7, sillage: 0.65, summerFriendly: 0.5,
    blurb: "Whipped cream-praline manis yang bikin nagih. Gourmand terjangkau paling laris.",
  },
  {
    id: "not-a-perfume",
    name: "Not a Perfume",
    brand: "Juliette Has a Gun",
    year: 2010,
    gender: "uni",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { musky: 0.6, woody: 0.4, ambery: 0.3 },
    notes: { top: [], heart: ["Ambroxan"], base: ["Ambroxan"] },
    longevity: 0.6, sillage: 0.5, summerFriendly: 0.8,
    blurb: "Satu bahan (Ambroxan) — musk-ambergris bersih & minimalis. 'Aroma tapi bukan parfum'.",
  },
  {
    id: "beach-walk",
    name: "Replica Beach Walk EDT",
    brand: "Maison Margiela",
    year: 2012,
    gender: "uni",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { white_floral: 0.4, sweet: 0.4, musky: 0.4, aquatic_ozonic: 0.4, powdery: 0.3 },
    notes: { top: ["Bergamot", "Lemon", "Pink pepper"], heart: ["Coconut milk", "Ylang-ylang"], base: ["Musk", "Cedar", "Benzoin"] },
    longevity: 0.55, sillage: 0.5, summerFriendly: 0.9,
    blurb: "Kelapa-suncream-ylang yang bikin kebayang pantai. Segar-manis buat panas.",
  },
  {
    id: "lazy-sunday-morning",
    name: "Replica Lazy Sunday Morning EDT",
    brand: "Maison Margiela",
    year: 2011,
    gender: "uni",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { musky: 0.6, floral: 0.4, powdery: 0.4, fresh: 0.3 },
    notes: { top: ["Aldehydes", "Pear"], heart: ["Rose", "Iris", "Lily"], base: ["Musk", "White woods"] },
    longevity: 0.6, sillage: 0.5, summerFriendly: 0.8,
    blurb: "Musk-iris seperti sprei bersih habis dijemur. Clean, nyaman, effortless.",
  },
  {
    id: "herod",
    name: "Herod EDP",
    brand: "Parfums de Marly",
    year: 2012,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { spicy_warm: 0.6, gourmand: 0.5, vanilla: 0.5, woody: 0.4, sweet: 0.4 },
    notes: { top: ["Pepper", "Cinnamon"], heart: ["Tobacco leaf", "Osmanthus"], base: ["Vanilla", "Vetiver", "Cedar"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.35,
    blurb: "Tembakau-vanila-kayu manis yang mewah & hangat. Musim dingin/AC banget.",
  },
  {
    id: "pegasus",
    name: "Pegasus EDP",
    brand: "Parfums de Marly",
    year: 2011,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { gourmand: 0.6, vanilla: 0.5, sweet: 0.5, powdery: 0.4, aromatic: 0.3 },
    notes: { top: ["Bergamot", "Bitter almond"], heart: ["Heliotrope", "Jasmine"], base: ["Vanilla", "Sandalwood"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.5,
    blurb: "Almond-vanila-heliotrope yang creamy & elegan. Gourmand cowok yang classy.",
  },
  {
    id: "oud-satin-mood",
    name: "Oud Satin Mood EDP",
    brand: "Maison Francis Kurkdjian",
    year: 2015,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4,5jt–6,5jt",
    accords: { ambery: 0.6, floral: 0.5, vanilla: 0.5, animalic: 0.4, sweet: 0.4, powdery: 0.3 },
    notes: { top: ["Violet"], heart: ["Rose", "Oud"], base: ["Vanilla", "Benzoin", "Amber"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.3,
    blurb: "Mawar-oud-vanila yang lembut & mewah. Sensual, malam, cuaca dingin.",
  },
  {
    id: "another-13",
    name: "Another 13",
    brand: "Le Labo",
    year: 2010,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { musky: 0.6, ambery: 0.5, woody: 0.4, fresh: 0.3 },
    notes: { top: ["Ambrette", "Pear"], heart: ["Ambrox", "Jasmine"], base: ["Moss", "Musk", "Ambergris"] },
    longevity: 0.7, sillage: 0.6, summerFriendly: 0.7,
    blurb: "Ambroxan-musk clean yang adiktif & uniseks. 'Aroma futuristik' minimalis.",
  },
  {
    id: "lost-cherry",
    name: "Lost Cherry EDP",
    brand: "Tom Ford",
    year: 2018,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4,5jt–6,5jt",
    accords: { sweet: 0.7, fruity: 0.6, gourmand: 0.5, vanilla: 0.4, ambery: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Black cherry", "Cherry liqueur", "Almond"], heart: ["Turkish rose", "Jasmine"], base: ["Tonka", "Vanilla", "Cinnamon"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    blurb: "Ceri-almond-liqueur yang manis & genit. Statement gourmand mahal.",
  },
  {
    id: "bitter-peach",
    name: "Bitter Peach EDP",
    brand: "Tom Ford",
    year: 2020,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4,5jt–6,5jt",
    accords: { fruity: 0.7, sweet: 0.6, gourmand: 0.5, ambery: 0.3, vanilla: 0.3 },
    notes: { top: ["Peach", "Blood orange", "Cardamom"], heart: ["Rum", "Davana"], base: ["Vanilla", "Sandalwood", "Tonka"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.45,
    blurb: "Persik-rum manis yang lezat & mewah. Buah gourmand buat malam.",
  },
  {
    id: "erba-pura",
    name: "Erba Pura EDP",
    brand: "Xerjoff",
    year: 2015,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { fruity: 0.6, citrus: 0.5, ambery: 0.4, sweet: 0.4, musky: 0.3 },
    notes: { top: ["Sicilian orange", "Fruits"], heart: ["White flowers"], base: ["Amber", "Musk", "Vanilla"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.6,
    blurb: "Jeruk-buah-amber yang cerah & juicy. Crowd-pleaser mahal yang serba suasana.",
  },
  {
    id: "green-irish-tweed",
    name: "Green Irish Tweed",
    brand: "Creed",
    year: 1985,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp4jt–6jt",
    accords: { fresh: 0.6, floral: 0.4, woody: 0.4, aromatic: 0.4, citrus: 0.3 },
    notes: { top: ["Lemon verbena", "Iris"], heart: ["Violet leaf"], base: ["Sandalwood", "Ambergris"] },
    longevity: 0.7, sillage: 0.6, summerFriendly: 0.8,
    blurb: "Hijau-violet-sandalwood yang klasik & gentleman. Segar elegan sepanjang masa.",
  },
  {
    id: "silver-mountain-water",
    name: "Silver Mountain Water",
    brand: "Creed",
    year: 1995,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–6jt",
    accords: { citrus: 0.6, fresh: 0.6, musky: 0.4, fruity: 0.3 },
    notes: { top: ["Bergamot", "Mandarin"], heart: ["Green tea", "Blackcurrant"], base: ["Musk", "Sandalwood"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.9,
    blurb: "Teh hijau-blackcurrant-musk yang bersih seperti udara gunung. Segar mewah buat panas.",
  },
  {
    id: "gypsy-water",
    name: "Gypsy Water EDP",
    brand: "Byredo",
    year: 2008,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { woody: 0.6, fresh: 0.4, vanilla: 0.4, aromatic: 0.4, ambery: 0.3 },
    notes: { top: ["Bergamot", "Lemon", "Pepper"], heart: ["Pine needles", "Incense"], base: ["Sandalwood", "Amber", "Vanilla"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.7,
    blurb: "Pinus-sandalwood-vanila yang kering & bohemian. Woody lembut yang gampang disuka.",
  },
  {
    id: "mojave-ghost",
    name: "Mojave Ghost EDP",
    brand: "Byredo",
    year: 2014,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { woody: 0.5, floral: 0.4, musky: 0.4, powdery: 0.3, fruity: 0.3 },
    notes: { top: ["Ambrette", "Nesberry"], heart: ["Violet", "Magnolia"], base: ["Sandalwood", "Cedar", "Musk"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.75,
    blurb: "Woody-violet-ambrette yang halus & 'aura'. Skin scent mahal yang tenang.",
  },
  {
    id: "interlude-man",
    name: "Interlude Man",
    brand: "Amouage",
    year: 2012,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp4,5jt–6,5jt",
    accords: { smoky: 0.7, spicy_warm: 0.5, leather: 0.5, animalic: 0.4, woody: 0.4, mossy_chypre: 0.3 },
    notes: { top: ["Bergamot", "Oregano", "Pimento"], heart: ["Incense", "Amber", "Cistus"], base: ["Leather", "Oud", "Patchouli"] },
    longevity: 0.9, sillage: 0.9, summerFriendly: 0.3,
    blurb: "Dupa-rempah-kulit yang 'kabut asap' pekat. Statement berani buat cuaca dingin.",
  },
  {
    id: "hacivat",
    name: "Hacivat EDP",
    brand: "Nishane",
    year: 2017,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–6jt",
    accords: { fruity: 0.6, mossy_chypre: 0.5, woody: 0.5, smoky: 0.3, citrus: 0.3 },
    notes: { top: ["Pineapple", "Bergamot", "Grapefruit"], heart: ["Cypress", "Jasmine"], base: ["Oakmoss", "Patchouli", "Cedar"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.6,
    blurb: "Nanas-cypress-oakmoss yang segar tapi mewah. Aventus-nya penggemar niche.",
  },
  {
    id: "yara",
    name: "Yara EDP",
    brand: "Lattafa",
    year: 2020,
    gender: "fem",
    priceTier: 1,
    priceIDR: "Rp200rb–350rb",
    accords: { sweet: 0.6, fruity: 0.5, vanilla: 0.5, gourmand: 0.4, white_floral: 0.3 },
    notes: { top: ["Heliotrope", "Tropical fruits"], heart: ["Orchid", "Jasmine"], base: ["Vanilla", "Sandalwood", "Musk"] },
    longevity: 0.8, sillage: 0.8, summerFriendly: 0.5,
    blurb: "Manis-tropis-vanila yang viral & murah. Feminin nagih buat penyuka manis.",
  },
  {
    id: "fakhar",
    name: "Fakhar Black",
    brand: "Lattafa",
    year: 2021,
    gender: "masc",
    priceTier: 1,
    priceIDR: "Rp200rb–350rb",
    accords: { fresh: 0.5, spicy_fresh: 0.5, ambery: 0.4, woody: 0.4, citrus: 0.4 },
    notes: { top: ["Bergamot", "Pepper"], heart: ["Lavender", "Geranium"], base: ["Ambroxan", "Cedar"] },
    longevity: 0.8, sillage: 0.8, summerFriendly: 0.7,
    dupeOf: "sauvage",
    blurb: "Fresh-spicy ambroxan mirip Sauvage, harga sepersepuluh. Value gila buat harian.",
  },
  {
    id: "cdn-sillage",
    name: "Club de Nuit Sillage",
    brand: "Armaf",
    year: 2019,
    gender: "uni",
    priceTier: 2,
    priceIDR: "Rp350rb–550rb",
    accords: { citrus: 0.5, aquatic_ozonic: 0.5, fresh: 0.5, fruity: 0.4, woody: 0.3, musky: 0.3 },
    notes: { top: ["Green notes", "Pineapple", "Bergamot"], heart: ["Jasmine", "Lily"], base: ["Ambroxan", "Musk"] },
    longevity: 0.8, sillage: 0.85, summerFriendly: 0.85,
    blurb: "Segar-nanas-ambroxan yang cerah & tembus. Performa monster buat panas.",
  },
  {
    id: "hawas",
    name: "Hawas for Him",
    brand: "Rasasi",
    year: 2016,
    gender: "masc",
    priceTier: 2,
    priceIDR: "Rp350rb–550rb",
    accords: { aquatic_ozonic: 0.5, fresh: 0.5, fruity: 0.4, citrus: 0.4, woody: 0.3, ambery: 0.3 },
    notes: { top: ["Apple", "Bergamot", "Cinnamon"], heart: ["Ambergris", "Rose"], base: ["Musk", "Oakmoss", "Amber"] },
    longevity: 0.8, sillage: 0.8, summerFriendly: 0.8,
    blurb: "Aquatic-apel-ambergris yang crowd-pleaser & tahan lama. Fresh murah yang naik daun.",
  },
  {
    id: "amber-oud-gold",
    name: "Amber Oud Gold Edition",
    brand: "Al Haramain",
    year: 2017,
    gender: "uni",
    priceTier: 2,
    priceIDR: "Rp300rb–500rb",
    accords: { fruity: 0.6, sweet: 0.5, ambery: 0.4, citrus: 0.4, musky: 0.3 },
    notes: { top: ["Fruity notes", "Orange"], heart: ["White flowers"], base: ["Amber", "Musk"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.6,
    dupeOf: "erba-pura",
    blurb: "Jeruk-buah-amber mirip Erba Pura, seperlima harga. Cerah & juicy buat harian.",
  },
  {
    id: "ana-abiyedh-rouge",
    name: "Ana Abiyedh Rouge",
    brand: "Lattafa",
    year: 2019,
    gender: "uni",
    priceTier: 1,
    priceIDR: "Rp180rb–320rb",
    accords: { citrus: 0.6, fresh: 0.5, aromatic: 0.4, woody: 0.3, musky: 0.3 },
    notes: { top: ["Bergamot", "Lemon"], heart: ["Green tea", "Herbs"], base: ["Musk", "Cedar"] },
    longevity: 0.7, sillage: 0.65, summerFriendly: 0.9,
    blurb: "Citrus-teh bersih yang murah meriah. Segar simpel buat gerah sehari-hari.",
  },
  {
    id: "amethyst",
    name: "Bade'e Al Oud Amethyst",
    brand: "Lattafa",
    year: 2022,
    gender: "uni",
    priceTier: 2,
    priceIDR: "Rp300rb–500rb",
    accords: { sweet: 0.6, fruity: 0.6, gourmand: 0.4, animalic: 0.3, ambery: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Black cherry", "Cinnamon"], heart: ["Rose", "Praline"], base: ["Oud", "Vanilla", "Tonka"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    dupeOf: "lost-cherry",
    blurb: "Ceri-oud-praline mirip Lost Cherry, jauh lebih murah. Manis genit buat malam.",
  },
  {
    id: "peony-blush-suede",
    name: "Peony & Blush Suede Cologne",
    brand: "Jo Malone",
    year: 2013,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { floral: 0.6, fruity: 0.4, powdery: 0.3, musky: 0.3 },
    notes: { top: ["Peony", "Red apple"], heart: ["Rose", "Freesia"], base: ["Suede"] },
    longevity: 0.55, sillage: 0.5, summerFriendly: 0.85,
    blurb: "Peony-apel-suede yang lembut & elegan. Feminin ringan buat harian rapi.",
  },
  {
    id: "mon-guerlain",
    name: "Mon Guerlain EDP",
    brand: "Guerlain",
    year: 2017,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { vanilla: 0.6, aromatic: 0.5, sweet: 0.4, floral: 0.4, powdery: 0.3 },
    notes: { top: ["Bergamot", "Lavender"], heart: ["Jasmine", "Iris"], base: ["Vanilla", "Tonka", "Sandalwood"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.55,
    blurb: "Lavender-vanila-iris yang creamy & anggun. Feminin dewasa yang cozy.",
  },
  {
    id: "angel",
    name: "Angel EDP",
    brand: "Mugler",
    year: 1992,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,4jt",
    accords: { gourmand: 0.8, sweet: 0.6, mossy_chypre: 0.5, vanilla: 0.4, fruity: 0.3 },
    notes: { top: ["Bergamot", "Melon"], heart: ["Honey", "Red berries", "Chocolate"], base: ["Praline", "Patchouli", "Caramel"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.35,
    blurb: "Cokelat-praline-patchouli yang legendaris & polarizing. Gourmand bomba buat malam dingin.",
  },
  {
    id: "alien",
    name: "Alien EDP",
    brand: "Mugler",
    year: 2005,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,4jt",
    accords: { white_floral: 0.7, ambery: 0.5, woody: 0.4, powdery: 0.3 },
    notes: { top: ["Jasmine"], heart: ["Cashmeran"], base: ["Amber", "White woods"] },
    longevity: 0.9, sillage: 0.85, summerFriendly: 0.5,
    blurb: "Jasmine-amber-cashmeran yang pekat & hipnotis. Bunga putih statement buat malam.",
  },
  {
    id: "invictus",
    name: "Invictus",
    brand: "Paco Rabanne",
    year: 2013,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,5jt",
    accords: { aquatic_ozonic: 0.6, citrus: 0.5, fresh: 0.5, woody: 0.3, ambery: 0.3 },
    notes: { top: ["Grapefruit", "Marine notes"], heart: ["Bay leaf", "Jasmine"], base: ["Guaiac wood", "Ambergris", "Oakmoss"] },
    longevity: 0.7, sillage: 0.7, summerFriendly: 0.9,
    blurb: "Aquatic-grapefruit yang seger & sporty. Crowd-pleaser anak muda buat siang.",
  },
  {
    id: "terre-dhermes",
    name: "Terre d'Hermès EDT",
    brand: "Hermès",
    year: 2006,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { woody: 0.6, citrus: 0.5, spicy_fresh: 0.4, mossy_chypre: 0.3, aromatic: 0.3 },
    notes: { top: ["Orange", "Grapefruit"], heart: ["Pepper", "Geranium"], base: ["Vetiver", "Cedar", "Flint"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.7,
    blurb: "Jeruk-vetiver-flint yang maskulin & 'bumi'. Elegan, matang, serba suasana.",
  },
  {
    id: "dior-homme",
    name: "Dior Homme (2020)",
    brand: "Dior",
    year: 2020,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,3jt",
    accords: { powdery: 0.6, floral: 0.4, woody: 0.5, gourmand: 0.3, ambery: 0.3 },
    notes: { top: ["Bergamot"], heart: ["Iris", "Cashmere wood"], base: ["Cacao", "Vetiver", "Patchouli"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Iris-cacao-kayu yang lembut & sophisticated. Cowok well-groomed banget.",
  },
  {
    id: "armani-code",
    name: "Armani Code",
    brand: "Giorgio Armani",
    year: 2004,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,6jt",
    accords: { aromatic: 0.5, sweet: 0.5, woody: 0.4, ambery: 0.3, citrus: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Bergamot", "Lemon"], heart: ["Olive blossom", "Star anise"], base: ["Tonka", "Leather", "Tobacco"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Tonka-anise-kulit yang seductive & smooth. Aroma malam yang classy.",
  },
  {
    id: "stronger-with-you",
    name: "Stronger With You",
    brand: "Emporio Armani",
    year: 2017,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,7jt",
    accords: { sweet: 0.6, spicy_warm: 0.5, gourmand: 0.5, vanilla: 0.4, aromatic: 0.3 },
    notes: { top: ["Cardamom", "Pink pepper"], heart: ["Sage", "Chestnut"], base: ["Vanilla", "Amberwood", "Cedar"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.5,
    blurb: "Kastanye-vanila-kardamom yang manis nagih. Favorit anak muda buat kencan.",
  },
  {
    id: "the-one-men",
    name: "The One for Men EDP",
    brand: "Dolce & Gabbana",
    year: 2015,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1jt–1,6jt",
    accords: { spicy_warm: 0.6, ambery: 0.5, woody: 0.4, gourmand: 0.3, citrus: 0.3 },
    notes: { top: ["Grapefruit", "Coriander", "Basil"], heart: ["Cardamom", "Ginger", "Orange blossom"], base: ["Tobacco", "Amber", "Cedar"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.55,
    blurb: "Rempah-tembakau-amber yang hangat & rapi. Aman buat kantor sampai malam.",
  },
  {
    id: "ultra-male",
    name: "Ultra Male",
    brand: "Jean Paul Gaultier",
    year: 2015,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,7jt",
    accords: { sweet: 0.7, aromatic: 0.5, vanilla: 0.5, fruity: 0.4, gourmand: 0.3 },
    notes: { top: ["Pear", "Bergamot", "Mint"], heart: ["Lavender", "Cinnamon"], base: ["Vanilla", "Amber", "Cedar"] },
    longevity: 0.85, sillage: 0.85, summerFriendly: 0.5,
    blurb: "Pear-lavender-vanila manis yang bikin nagih. Proyeksi galak buat malam.",
  },
  {
    id: "spicebomb",
    name: "Spicebomb",
    brand: "Viktor&Rolf",
    year: 2012,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { spicy_warm: 0.7, leather: 0.4, woody: 0.4, ambery: 0.4, gourmand: 0.3 },
    notes: { top: ["Grapefruit", "Chili", "Pink pepper"], heart: ["Cinnamon", "Saffron"], base: ["Tobacco", "Leather", "Vetiver"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.4,
    blurb: "Ledakan rempah-tembakau-kulit yang berani. Hangat, maskulin, buat cuaca sejuk.",
  },
  {
    id: "cool-water",
    name: "Cool Water",
    brand: "Davidoff",
    year: 1988,
    gender: "masc",
    priceTier: 1,
    priceIDR: "Rp250rb–450rb",
    accords: { aquatic_ozonic: 0.7, aromatic: 0.5, fresh: 0.5, musky: 0.3, woody: 0.3 },
    notes: { top: ["Sea water", "Mint", "Lavender"], heart: ["Geranium", "Sandalwood"], base: ["Musk", "Amber", "Tobacco"] },
    longevity: 0.6, sillage: 0.6, summerFriendly: 0.9,
    blurb: "Aquatic-mint legendaris & murah. Nostalgia '90an yang tetap segar buat panas.",
  },
  {
    id: "azzaro-chrome",
    name: "Chrome",
    brand: "Azzaro",
    year: 1996,
    gender: "masc",
    priceTier: 2,
    priceIDR: "Rp500rb–900rb",
    accords: { citrus: 0.6, fresh: 0.5, aromatic: 0.4, aquatic_ozonic: 0.4, musky: 0.3 },
    notes: { top: ["Lemon", "Pineapple", "Bergamot"], heart: ["Jasmine", "Cyclamen"], base: ["Musk", "Oakmoss", "Tonka"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.9,
    blurb: "Citrus-musk bersih yang klasik & fresh. Wangi 'cowok rapi' buat siang gerah.",
  },
  {
    id: "issey-homme",
    name: "L'Eau d'Issey Pour Homme",
    brand: "Issey Miyake",
    year: 1994,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { aquatic_ozonic: 0.7, citrus: 0.5, woody: 0.4, spicy_warm: 0.3, aromatic: 0.3 },
    notes: { top: ["Yuzu", "Bergamot", "Tarragon"], heart: ["Nutmeg", "Lily", "Cinnamon"], base: ["Sandalwood", "Vetiver", "Musk"] },
    longevity: 0.7, sillage: 0.6, summerFriendly: 0.9,
    blurb: "Yuzu-aquatic-woody yang bersih & tenang. Segar minimalis buat harian panas.",
  },
  {
    id: "noir-extreme",
    name: "Noir Extreme EDP",
    brand: "Tom Ford",
    year: 2015,
    gender: "masc",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { ambery: 0.6, gourmand: 0.5, spicy_warm: 0.5, vanilla: 0.4, sweet: 0.4 },
    notes: { top: ["Cardamom", "Nutmeg", "Saffron"], heart: ["Kulfi", "Orange blossom"], base: ["Amber", "Vanilla", "Sandalwood"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    blurb: "Kardamom-kulfi-amber yang manis mewah. Seductive banget buat malam.",
  },
  {
    id: "ombre-leather",
    name: "Ombré Leather EDP",
    brand: "Tom Ford",
    year: 2018,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { leather: 0.7, floral: 0.4, ambery: 0.4, woody: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Cardamom"], heart: ["Leather", "Jasmine"], base: ["Amber", "Patchouli", "Moss"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Kulit-jasmine-amber yang smooth & uniseks. Statement kulit yang gampang dipakai.",
  },
  {
    id: "boss-bottled",
    name: "Boss Bottled",
    brand: "Hugo Boss",
    year: 1998,
    gender: "masc",
    priceTier: 2,
    priceIDR: "Rp600rb–1jt",
    accords: { fruity: 0.5, spicy_warm: 0.4, woody: 0.4, aromatic: 0.3, sweet: 0.3 },
    notes: { top: ["Apple", "Bergamot", "Lemon"], heart: ["Cinnamon", "Geranium", "Carnation"], base: ["Sandalwood", "Vetiver", "Vanilla"] },
    longevity: 0.7, sillage: 0.65, summerFriendly: 0.6,
    blurb: "Apel-kayu manis-woody yang matang & profesional. Wangi kantor sejuta umat.",
  },
  {
    id: "gentleman",
    name: "Gentleman EDP",
    brand: "Givenchy",
    year: 2018,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { floral: 0.4, powdery: 0.4, leather: 0.4, woody: 0.4, fruity: 0.3, ambery: 0.3 },
    notes: { top: ["Pear", "Cardamom"], heart: ["Iris", "Lavender"], base: ["Leather", "Patchouli", "Black vanilla"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.5,
    blurb: "Iris-pear-kulit yang modern & percaya diri. Rapi tapi ada 'gigit'-nya.",
  },
  {
    id: "bad-boy",
    name: "Bad Boy",
    brand: "Carolina Herrera",
    year: 2019,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { spicy_warm: 0.5, gourmand: 0.5, sweet: 0.5, woody: 0.3, ambery: 0.3 },
    notes: { top: ["Pepper", "Bergamot"], heart: ["Sage", "Cinnamon"], base: ["Cacao", "Tonka", "Amberwood"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.5,
    blurb: "Cacao-lada-tonka yang manis-nakal. Versi cowok dari Good Girl, buat malam.",
  },
  {
    id: "212-vip-men",
    name: "212 VIP Men",
    brand: "Carolina Herrera",
    year: 2011,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,6jt",
    accords: { sweet: 0.5, gourmand: 0.4, citrus: 0.4, ambery: 0.3, spicy_warm: 0.3 },
    notes: { top: ["Lime", "Frozen mint", "Vodka"], heart: ["Ginger", "Black pepper"], base: ["Amber", "Leather", "Tonka"] },
    longevity: 0.75, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Lime-vodka-amber manis yang party banget. Vibe clubbing anak muda.",
  },
  {
    id: "phantom",
    name: "Phantom",
    brand: "Paco Rabanne",
    year: 2021,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,7jt",
    accords: { fresh: 0.5, aromatic: 0.5, vanilla: 0.4, citrus: 0.4, sweet: 0.3 },
    notes: { top: ["Lemon", "Lavender"], heart: ["Vanilla", "Cardamom"], base: ["Patchouli", "Vetiver"] },
    longevity: 0.75, sillage: 0.7, summerFriendly: 0.7,
    blurb: "Lemon-lavender-vanila yang fresh sekaligus manis. Serba bisa, gampang disuka.",
  },
  {
    id: "luna-rossa-ocean",
    name: "Luna Rossa Ocean",
    brand: "Prada",
    year: 2019,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { fresh: 0.5, aquatic_ozonic: 0.5, woody: 0.4, citrus: 0.4, ambery: 0.3 },
    notes: { top: ["Bergamot", "Bitter orange"], heart: ["Sage", "Cardamom"], base: ["Ambroxan", "Patchouli", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.85,
    blurb: "Fresh-ambroxan-woody yang bersih & tahan. Segar 'naik kelas' buat panas.",
  },
  {
    id: "angels-share",
    name: "Angels' Share",
    brand: "Kilian",
    year: 2020,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { gourmand: 0.7, sweet: 0.6, spicy_warm: 0.5, vanilla: 0.4, ambery: 0.3 },
    notes: { top: ["Cognac"], heart: ["Cinnamon", "Tonka", "Oak"], base: ["Praline", "Vanilla", "Sandalwood"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.35,
    blurb: "Cognac-praline-kayu manis yang mewah & 'boozy'. Gourmand malam yang mewah.",
  },
  {
    id: "jazz-club",
    name: "Replica Jazz Club EDT",
    brand: "Maison Margiela",
    year: 2013,
    gender: "masc",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { gourmand: 0.6, sweet: 0.5, spicy_warm: 0.4, vanilla: 0.4, woody: 0.3, smoky: 0.3 },
    notes: { top: ["Pink pepper", "Neroli", "Lemon"], heart: ["Rum", "Tobacco leaf"], base: ["Vanilla", "Tonka", "Vetiver"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.4,
    blurb: "Rum-tembakau-vanila yang cozy kayak bar jazz. Hangat, dewasa, nagih.",
  },
  {
    id: "valentino-uomo",
    name: "Uomo Born in Roma",
    brand: "Valentino",
    year: 2019,
    gender: "masc",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { aromatic: 0.5, woody: 0.4, vanilla: 0.4, spicy_fresh: 0.3, ambery: 0.3 },
    notes: { top: ["Ginger", "Bergamot"], heart: ["Sage", "Violet leaf"], base: ["Vanilla", "Cedar", "Tobacco"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.6,
    blurb: "Sage-vanila-woody yang modern & clean. Serba bisa buat cowok muda.",
  },
  {
    id: "jadore",
    name: "J'adore EDP",
    brand: "Dior",
    year: 1999,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { floral: 0.7, white_floral: 0.5, fruity: 0.3, powdery: 0.3 },
    notes: { top: ["Pear", "Melon", "Bergamot"], heart: ["Jasmine", "Rose", "Ylang-ylang"], base: ["Musk", "Vanilla", "Cedar"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Buket bunga mewah yang feminin & anggun. Klasik elegan sepanjang masa.",
  },
  {
    id: "miss-dior",
    name: "Miss Dior EDP (2021)",
    brand: "Dior",
    year: 2021,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { floral: 0.7, fruity: 0.4, mossy_chypre: 0.3, powdery: 0.3, sweet: 0.3 },
    notes: { top: ["Blood orange", "Pink pepper"], heart: ["Rose", "Peony", "Iris"], base: ["Rosewood", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.65,
    blurb: "Mawar-peony segar-manis yang romantis. Feminin buat harian sampai kencan.",
  },
  {
    id: "hypnotic-poison",
    name: "Hypnotic Poison EDT",
    brand: "Dior",
    year: 1998,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,3jt",
    accords: { vanilla: 0.7, sweet: 0.6, gourmand: 0.5, spicy_warm: 0.4, ambery: 0.3 },
    notes: { top: ["Apricot", "Plum", "Coconut"], heart: ["Jasmine", "Caraway"], base: ["Vanilla", "Almond", "Musk"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    blurb: "Vanila-almond-rempah yang hipnotis & sensual. Manis gelap buat malam.",
  },
  {
    id: "armani-si",
    name: "Sì EDP",
    brand: "Giorgio Armani",
    year: 2013,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,3jt",
    accords: { fruity: 0.5, ambery: 0.4, mossy_chypre: 0.4, vanilla: 0.4, floral: 0.4, sweet: 0.4 },
    notes: { top: ["Blackcurrant", "Bergamot"], heart: ["Rose", "Freesia"], base: ["Vanilla", "Patchouli", "Amber"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.55,
    blurb: "Blackcurrant-vanila-chypre yang modern & chic. Feminin dewasa yang klasik.",
  },
  {
    id: "my-way",
    name: "My Way EDP",
    brand: "Giorgio Armani",
    year: 2020,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,3jt",
    accords: { white_floral: 0.5, floral: 0.5, vanilla: 0.4, musky: 0.3, powdery: 0.3 },
    notes: { top: ["Orange blossom", "Bergamot"], heart: ["Tuberose", "Jasmine"], base: ["Vanilla", "Cedar", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Bunga jeruk-tuberose-vanila yang cerah & lembut. Feminin modern serba suasana.",
  },
  {
    id: "lady-million",
    name: "Lady Million",
    brand: "Paco Rabanne",
    year: 2010,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { floral: 0.5, sweet: 0.5, ambery: 0.4, fruity: 0.4, mossy_chypre: 0.3 },
    notes: { top: ["Raspberry", "Neroli", "Lemon"], heart: ["Jasmine", "Orange blossom"], base: ["Honey", "Patchouli", "Amber"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.55,
    blurb: "Raspberry-honey-patchouli yang glamor & manis. Feminin bold buat 'tampil'.",
  },
  {
    id: "olympea",
    name: "Olympéa",
    brand: "Paco Rabanne",
    year: 2015,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { vanilla: 0.5, sweet: 0.5, aquatic_ozonic: 0.4, white_floral: 0.4, ambery: 0.3 },
    notes: { top: ["Water jasmine", "Mandarin", "Green notes"], heart: ["Salt", "Ginger lily"], base: ["Vanilla", "Amber", "Sandalwood"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.6,
    blurb: "Vanila-garam yang manis-asin unik & nagih. Sensual tapi tetap fresh.",
  },
  {
    id: "bright-crystal",
    name: "Bright Crystal",
    brand: "Versace",
    year: 2006,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp900rb–1,4jt",
    accords: { fruity: 0.6, floral: 0.5, fresh: 0.4, musky: 0.3 },
    notes: { top: ["Pomegranate", "Yuzu", "Iced accord"], heart: ["Peony", "Magnolia", "Lotus"], base: ["Musk", "Amber", "Mahogany"] },
    longevity: 0.6, sillage: 0.6, summerFriendly: 0.9,
    blurb: "Pomegranate-peony segar-manis yang ringan. Feminin ceria buat harian panas.",
  },
  {
    id: "chance-edp",
    name: "Chance EDP",
    brand: "Chanel",
    year: 2003,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,8jt–2,6jt",
    accords: { floral: 0.6, spicy_fresh: 0.4, ambery: 0.3, powdery: 0.3, citrus: 0.3 },
    notes: { top: ["Pink pepper", "Lemon"], heart: ["Jasmine", "Iris"], base: ["Patchouli", "Vetiver", "Amber"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Lada pink-jasmine-patchouli yang chic & muter-muter. Feminin penuh gaya.",
  },
  {
    id: "gabrielle",
    name: "Gabrielle EDP",
    brand: "Chanel",
    year: 2017,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,9jt–2,7jt",
    accords: { white_floral: 0.7, floral: 0.5, fruity: 0.3, musky: 0.3 },
    notes: { top: ["Mandarin", "Blackcurrant"], heart: ["Jasmine", "Ylang-ylang", "Tuberose"], base: ["Sandalwood", "Musk"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.6,
    blurb: "Buket bunga putih yang cerah & 'bercahaya'. Feminin elegan yang modern.",
  },
  {
    id: "scandal",
    name: "Scandal",
    brand: "Jean Paul Gaultier",
    year: 2017,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { sweet: 0.5, floral: 0.5, gourmand: 0.4, white_floral: 0.4, mossy_chypre: 0.3 },
    notes: { top: ["Blood orange", "Mandarin"], heart: ["Honey", "Gardenia", "Jasmine"], base: ["Caramel", "Patchouli", "Beeswax"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.5,
    blurb: "Madu-gardenia-caramel yang manis genit. Feminin nagih buat malam.",
  },
  {
    id: "prada-candy",
    name: "Candy EDP",
    brand: "Prada",
    year: 2011,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,5jt–2,2jt",
    accords: { gourmand: 0.7, sweet: 0.7, vanilla: 0.5, powdery: 0.3 },
    notes: { top: ["Caramel"], heart: ["Benzoin"], base: ["Vanilla", "Musk", "Powdery notes"] },
    longevity: 0.8, sillage: 0.75, summerFriendly: 0.45,
    blurb: "Caramel-benzoin-vanila yang manis dekaden. Gourmand mewah buat sweet lover.",
  },
  {
    id: "shalimar",
    name: "Shalimar EDP",
    brand: "Guerlain",
    year: 1925,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,4jt",
    accords: { ambery: 0.6, vanilla: 0.6, powdery: 0.4, citrus: 0.3, animalic: 0.3 },
    notes: { top: ["Bergamot", "Lemon"], heart: ["Iris", "Jasmine", "Rose"], base: ["Vanilla", "Tonka", "Incense"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.35,
    blurb: "Amber-vanila-dupa oriental klasik & legendaris. Sensual, dewasa, timeless.",
  },
  {
    id: "tresor",
    name: "Trésor EDP",
    brand: "Lancôme",
    year: 1990,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,1jt–1,7jt",
    accords: { floral: 0.5, powdery: 0.5, fruity: 0.4, ambery: 0.4, vanilla: 0.3 },
    notes: { top: ["Apricot", "Peach", "Bergamot"], heart: ["Rose", "Iris", "Lilac"], base: ["Vanilla", "Amber", "Sandalwood"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.5,
    blurb: "Mawar-iris-apricot powdery yang hangat & anggun. Klasik 'wangi ibu' yang elegan.",
  },
  {
    id: "opium",
    name: "Opium EDP",
    brand: "YSL",
    year: 1977,
    gender: "fem",
    priceTier: 4,
    priceIDR: "Rp1,6jt–2,4jt",
    accords: { spicy_warm: 0.6, ambery: 0.5, floral: 0.4, powdery: 0.3, animalic: 0.3 },
    notes: { top: ["Mandarin", "Clove", "Coriander"], heart: ["Carnation", "Jasmine", "Myrrh"], base: ["Amber", "Patchouli", "Incense"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.3,
    blurb: "Cengkeh-myrrh-amber oriental yang pekat & dramatis. Statement malam yang berani.",
  },
  {
    id: "flora-gardenia",
    name: "Flora Gorgeous Gardenia",
    brand: "Gucci",
    year: 2012,
    gender: "fem",
    priceTier: 3,
    priceIDR: "Rp1,2jt–1,8jt",
    accords: { white_floral: 0.5, floral: 0.5, sweet: 0.5, fruity: 0.4 },
    notes: { top: ["Pear", "Red berries"], heart: ["Gardenia", "Jasmine"], base: ["Brown sugar", "Patchouli"] },
    longevity: 0.7, sillage: 0.65, summerFriendly: 0.65,
    blurb: "Gardenia-pear-brown sugar yang manis-bunga. Feminin playful buat harian.",
  },
  {
    id: "good-girl-gone-bad",
    name: "Good Girl Gone Bad",
    brand: "Kilian",
    year: 2012,
    gender: "fem",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { white_floral: 0.6, floral: 0.6, fruity: 0.3, ambery: 0.3, powdery: 0.3 },
    notes: { top: ["Osmanthus", "Indian jasmine"], heart: ["Tuberose", "Rose", "Narcissus"], base: ["Amber", "Cedar"] },
    longevity: 0.8, sillage: 0.7, summerFriendly: 0.55,
    blurb: "Tuberose-jasmine-osmanthus yang mewah & memikat. Bunga putih niche buat malam.",
  },
  {
    id: "portrait-of-a-lady",
    name: "Portrait of a Lady",
    brand: "Frédéric Malle",
    year: 2010,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp5jt–7jt",
    accords: { floral: 0.6, mossy_chypre: 0.5, spicy_warm: 0.4, smoky: 0.3, ambery: 0.3 },
    notes: { top: ["Turkish rose", "Blackcurrant", "Cinnamon"], heart: ["Clove", "Sandalwood"], base: ["Patchouli", "Incense", "Amber"] },
    longevity: 0.9, sillage: 0.9, summerFriendly: 0.35,
    blurb: "Mawar-patchouli-dupa yang pekat & agung. Mahakarya niche buat statement.",
  },
  {
    id: "bal-dafrique",
    name: "Bal d'Afrique EDP",
    brand: "Byredo",
    year: 2009,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { floral: 0.4, woody: 0.4, fresh: 0.4, citrus: 0.4, musky: 0.3 },
    notes: { top: ["Bergamot", "Lemon", "Neroli"], heart: ["Violet", "Jasmine", "Cyclamen"], base: ["Vetiver", "Cedar", "Musk"] },
    longevity: 0.6, sillage: 0.55, summerFriendly: 0.75,
    blurb: "Neroli-violet-vetiver yang cerah & 'vintage modern'. Woody-floral yang effortless.",
  },
  {
    id: "soleil-blanc",
    name: "Soleil Blanc",
    brand: "Tom Ford",
    year: 2016,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp4jt–5,5jt",
    accords: { sweet: 0.4, white_floral: 0.4, ambery: 0.4, aquatic_ozonic: 0.3, gourmand: 0.3 },
    notes: { top: ["Cardamom", "Bergamot", "Pistachio"], heart: ["Tuberose", "Ylang-ylang", "Coconut"], base: ["Amber", "Benzoin", "Tonka"] },
    longevity: 0.7, sillage: 0.65, summerFriendly: 0.7,
    blurb: "Kelapa-tuberose-amber yang 'liburan mewah'. Tropis manis buat panas & pantai.",
  },
  {
    id: "musc-ravageur",
    name: "Musc Ravageur",
    brand: "Frédéric Malle",
    year: 2000,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp5jt–7jt",
    accords: { musky: 0.5, vanilla: 0.5, ambery: 0.4, spicy_warm: 0.4, animalic: 0.4 },
    notes: { top: ["Bergamot", "Mandarin"], heart: ["Cinnamon", "Clove"], base: ["Musk", "Vanilla", "Amber", "Sandalwood"] },
    longevity: 0.85, sillage: 0.8, summerFriendly: 0.4,
    blurb: "Musk-vanila-rempah yang hangat & sensual banget. Skin scent seductive buat malam.",
  },
  {
    id: "rose-31",
    name: "Rose 31 EDP",
    brand: "Le Labo",
    year: 2006,
    gender: "uni",
    priceTier: 5,
    priceIDR: "Rp3,5jt–5jt",
    accords: { floral: 0.5, woody: 0.5, spicy_warm: 0.4, mossy_chypre: 0.3, aromatic: 0.3 },
    notes: { top: ["Rose", "Cumin"], heart: ["Gaiac wood", "Cedar"], base: ["Vetiver", "Musk", "Oud"] },
    longevity: 0.7, sillage: 0.6, summerFriendly: 0.55,
    blurb: "Mawar-kayu-cumin yang uniseks & 'nggak kecewekan'. Mawar buat semua gender.",
  },
];

/** Cari parfum berdasarkan id. */
export function findPerfume(id: string): Perfume | undefined {
  return PERFUMES.find((p) => p.id === id);
}
